options:
  mfa:
    active: true
    return_enroll_settings: true
  passwordPolicy: good
  strategy_version: 2
  brute_force_protection: true
strategy: auth0
name: Username-Password-Authentication
is_domain_connection: false
enabled_clients:
  - ceh6GiEdyU84dDhhxw7j6A4b5TmATi88
  - j2geSXdIU2qSkU9r09sfnNqJeuSVt5KH
  - 6Tukpwy2zvo9pSY1Xh465s6DRprAnfeK
