id: 5ea8183c0df9cb08beefe38c
name: Test Config API
identifier: https://test/config/api
allow_offline_access: false
skip_consent_for_verifiable_first_party_clients: true
token_lifetime: 86400
token_lifetime_for_web: 7200
signing_alg: RS256
