global: false
is_token_endpoint_ip_header_trusted: false
name: Default App
callbacks: []
is_first_party: true
oidc_conformant: true
sso_disabled: false
cross_origin_auth: false
client_id: 6Tukpwy2zvo9pSY1Xh465s6DRprAnfeK
callback_url_template: false
jwt_configuration:
  alg: RS256
  lifetime_in_seconds: 36000
  secret_encoded: false
grant_types:
  - authorization_code
  - implicit
  - refresh_token
  - client_credentials
custom_login_page_on: true
enabled_realms:
  - google-oauth2
  - Username-Password-Authentication
